-- ==========================================================
-- ONLINE ELECTION MANAGEMENT SYSTEM - ORACLE PL/SQL SCRIPT
-- ==========================================================

-- 1. DDL Statements (Data Definition Language)
-- Creating tables up to 3NF/BCNF with constraints

CREATE TABLE Election (
    election_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR2(20) NOT NULL CHECK(status IN ('Upcoming', 'Ongoing', 'Completed'))
);

CREATE TABLE Constituency (
    constituency_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE Voter (
    voter_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    constituency_id NUMBER NOT NULL,
    approval_status VARCHAR2(20) DEFAULT 'Pending' CHECK(approval_status IN ('Pending', 'Approved', 'Rejected')),
    CONSTRAINT fk_voter_constituency FOREIGN KEY (constituency_id) REFERENCES Constituency(constituency_id)
);

CREATE TABLE PoliticalParty (
    party_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_name VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE Candidate (
    candidate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    party_id NUMBER NOT NULL,
    election_id NUMBER NOT NULL,
    constituency_id NUMBER NOT NULL,
    approval_status VARCHAR2(20) DEFAULT 'Pending' CHECK(approval_status IN ('Pending', 'Approved', 'Rejected')),
    CONSTRAINT fk_candidate_party FOREIGN KEY (party_id) REFERENCES PoliticalParty(party_id),
    CONSTRAINT fk_candidate_election FOREIGN KEY (election_id) REFERENCES Election(election_id),
    CONSTRAINT fk_candidate_constituency FOREIGN KEY (constituency_id) REFERENCES Constituency(constituency_id)
);

CREATE TABLE Vote (
    vote_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voter_id NUMBER NOT NULL,
    candidate_id NUMBER NOT NULL,
    election_id NUMBER NOT NULL,
    vote_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vote_voter FOREIGN KEY (voter_id) REFERENCES Voter(voter_id),
    CONSTRAINT fk_vote_candidate FOREIGN KEY (candidate_id) REFERENCES Candidate(candidate_id),
    CONSTRAINT fk_vote_election FOREIGN KEY (election_id) REFERENCES Election(election_id),
    CONSTRAINT uq_vote_per_election UNIQUE (voter_id, election_id) -- Ensures one vote per voter per election
);

CREATE TABLE ElectionOfficer (
    officer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    role VARCHAR2(50) NOT NULL
);

CREATE TABLE AuditLog (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    action VARCHAR2(255) NOT NULL,
    log_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 2. PL/SQL Components
-- ==========================================================

-- Trigger to Automatically Insert Audit Log on Vote
CREATE OR REPLACE TRIGGER trg_audit_vote
AFTER INSERT ON Vote
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (user_id, action)
    VALUES (:NEW.voter_id, 'Casted vote for candidate ' || :NEW.candidate_id || ' in election ' || :NEW.election_id);
END;
/

-- Procedure to Cast Vote with Exception Handling & Transaction Management
CREATE OR REPLACE PROCEDURE cast_vote (
    p_voter_id NUMBER,
    p_candidate_id NUMBER,
    p_election_id NUMBER
) AS
    v_count NUMBER;
BEGIN
    -- Check if voter has already voted
    SELECT COUNT(*) INTO v_count FROM Vote WHERE voter_id = p_voter_id AND election_id = p_election_id;
    
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Voter has already cast a vote in this election.');
    END IF;

    -- Insert vote
    INSERT INTO Vote (voter_id, candidate_id, election_id)
    VALUES (p_voter_id, p_candidate_id, p_election_id);

    COMMIT; -- Success, commit transaction
    DBMS_OUTPUT.PUT_LINE('Vote cast successfully!');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK; -- If validation or insertion fails
        DBMS_OUTPUT.PUT_LINE('Error casting vote: ' || SQLERRM);
END;
/

-- Function to Calculate Vote Percentage for a Candidate
CREATE OR REPLACE FUNCTION get_vote_percentage(
    p_candidate_id NUMBER, 
    p_election_id NUMBER
) RETURN NUMBER IS
    t_votes NUMBER := 0;
    c_votes NUMBER := 0;
    v_percentage NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO t_votes FROM Vote WHERE election_id = p_election_id;
    SELECT COUNT(*) INTO c_votes FROM Vote WHERE candidate_id = p_candidate_id AND election_id = p_election_id;
    
    IF t_votes > 0 THEN
        v_percentage := (c_votes / t_votes) * 100;
    END IF;
    
    RETURN v_percentage;
END;
/

-- Cursor to Display Election Results
CREATE OR REPLACE PROCEDURE declare_results (p_election_id NUMBER) AS
    CURSOR c_results IS
        SELECT c.name, p.party_name, COUNT(v.vote_id) AS total_votes
        FROM Candidate c
        LEFT JOIN Vote v ON c.candidate_id = v.candidate_id
        JOIN PoliticalParty p ON c.party_id = p.party_id
        WHERE c.election_id = p_election_id
        GROUP BY c.name, p.party_name
        ORDER BY total_votes DESC;
BEGIN
    DBMS_OUTPUT.PUT_LINE('-------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('ELECTION RESULTS');
    DBMS_OUTPUT.PUT_LINE('-------------------------------------------');
    
    FOR r IN c_results LOOP
        DBMS_OUTPUT.PUT_LINE('Candidate: ' || r.name || ' | Party: ' || r.party_name || ' | Votes: ' || r.total_votes);
        DBMS_OUTPUT.PUT_LINE('Vote Share: ' || ROUND(get_vote_percentage(r.name, p_election_id), 2) || '%'); -- Assuming overloaded function or logic rewrite
    END LOOP;
END;
/

-- ==========================================================
-- 3. Inserting Sample Data
-- ==========================================================

INSERT INTO Constituency (name) VALUES ('North District');
INSERT INTO Constituency (name) VALUES ('South District');
INSERT INTO PoliticalParty (party_name) VALUES ('Progressive Alliance');
INSERT INTO PoliticalParty (party_name) VALUES ('Conservative Union');

INSERT INTO Election (name, start_date, end_date, status) 
VALUES ('General Election 2026', SYSDATE, SYSDATE + 1, 'Ongoing');

INSERT INTO Voter (name, email, password_hash, constituency_id) 
VALUES ('Alice', 'alice@email.com', 'hash', 1);

INSERT INTO Candidate (name, party_id, election_id, constituency_id) 
VALUES ('John Doe', 1, 1, 1);

INSERT INTO Candidate (name, party_id, election_id, constituency_id) 
VALUES ('Jane Roe', 2, 1, 1);

COMMIT;
